### ISSUE TITLE
Buffer not large enough for pixels

### ISSUE THREAD

**Issue by duard** [omerjerk/Screenshotter#2]
```
09-05 11:00:24.183 9896-9896/in.omerjerk.screenshotter D/AndroidRuntime: Shutting down VM
09-05 11:00:24.183 9896-9896/in.omerjerk.screenshotter E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: in.omerjerk.screenshotter, PID: 9896
                                                                         java.lang.RuntimeException: Buffer not large enough for pixels
                                                                             at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:535)
                                                                             at in.omerjerk.libscreenshotter.Screenshotter.onImageAvailable(Screenshotter.java:131)
                                                                             at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by amnazhatdinov** [comment]
Try it by replacing Bitmap.Config.ARGB_8888 to Bitmap.Config.RGB_565.

**Comment by CraftsmanHyj** [comment]
Try it by replacing Bitmap.Config.ARGB_8888 to Bitmap.Config.RGB_565.

not woking

**Comment by zyfdegh** [comment]
I changed to ALPHA_8 and it works.

**Comment by Junacik99** [comment]
@zyfdegh that must have been your use case. In my case I get java.lang.UnsupportedOperationException: bitmap must use ARGB_8888 config
